services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMKClub\Bundle\BasicsBundle\:
        resource: '../../'
        exclude: '../../{DMKClubBasicsBundle.php,Entity,Migrations,DependencyInjection}'

    DMKClub\Bundle\BasicsBundle\Controller\:
        public: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Qipsius\TCPDFBundle\Controller\TCPDFController: '@qipsius.tcpdf'

    DMKClub\Bundle\BasicsBundle\Utility\Datagrids:
        public: true

    DMKClub\Bundle\BasicsBundle\DataGrid\Extension\MassAction\DownloadPdfHandler:
        public: true

    DMKClub\Bundle\BasicsBundle\DataGrid\Extension\MassAction\ExportPdfAction:
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: dmkexportpdf }

    DMKClub\Bundle\BasicsBundle\DataGrid\Extension\MassAction\DownloadPdfAction:
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: dmkdownloadpdf }

# ###
# Datagrid Actions
# ###
    DMKClub\Bundle\BasicsBundle\DataGrid\Extension\Action\GetPdfAction:
        shared: false
        tags:
            - { name: oro_datagrid.extension.action.type, type: dmkgetpdf }
