channels:
   entity_data:
       -
          name: DMKClub\Bundle\SponsorBundle\Entity\Sponsor
          dependent:
              - DMKClub\Bundle\SponsorBundle\Entity\Category
              - DMKClub\Bundle\SponsorBundle\Entity\Contract
              - DMKClub\Bundle\SponsorBundle\Entity\ContractCategory
          navigation_items:
              - application_menu.customers_tab.dmkclub_sponsor
              - application_menu.sales_tab.dmkclub_sponsor_contract

   channel_types:
        sponsor:
            label: dmkclub.sponsor.channel_type.sponsor.label
            entities:
                - DMKClub\Bundle\SponsorBundle\Entity\Sponsor
                - DMKClub\Bundle\SponsorBundle\Entity\Category
            customer_identity: DMKClub\Bundle\SponsorBundle\Entity\Sponsor
            system: false
            priority: -20
