services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMKClub\Bundle\SponsorBundle\:
        resource: '../../'
        exclude: '../../{DMKClubSponsorBundle.php,DependencyInjection,Entity,Migrations,Model,Resources,Tests}'

    DMKClub\Bundle\SponsorBundle\Controller\:
        public: true
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

# ###
# Autocomplete Search Handler
# ###
    dmkclub_sponsor.form.autocomplete.category.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - 'DMKClub\Bundle\SponsorBundle\Entity\Category'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: dmkclub_sponsorcategories, acl_resource: dmkclub_sponsorcategory_view }

    dmkclub_sponsor.form.autocomplete.contractcategory.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - 'DMKClub\Bundle\SponsorBundle\Entity\ContractCategory'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: dmkclub_sponsor_contractcategories, acl_resource: dmkclub_sponsor_contractcategory_view }
